[package]
name = "jh_admin_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
dotenv = "0.15.0"
ldap3 = "0.11.5"
reqwest = "0.12.18"
serde = "1.0.219"
serde_json = "1.0.140"
